agent_class: 'agents.OMD_with_Virtual_Transition_Weighted_Negentropy_Regularization.OMD_with_Virtual_Transition_Weighted_Negentropy_Regularization'

init_kwargs:
  lr_constant: 1.0
  lr_pow_X: 0.0
  lr_pow_A: 0.0
  lr_pow_H: 0.0
  lr_pow_T: 0.0
  ix_constant: 0.05
  ix_pow_X: 0.0
  ix_pow_A: 0.0
  ix_pow_H: 0.0
  ix_pow_T: 0.0
  T: 10
  Opt: 1
  KK: 100
  
  name: 'Ours'